### ISSUE TITLE
Question: How has this worked?

### ISSUE THREAD

**Issue by jmfury** [adolfodepazvela/vagrant-aem#1]
Hi Adolfo, 

I am keen to give this a try. Has it worked for you well? 

I am needing to onboard some of my team to an AEM project (none of us native AEM devs). 

Any info or ideas are hugely appreciated. And thanks very much for putting this out there!

**Comment by adolfodepazvela** [comment]
Hi Jimmi,
Yes, it works well, but now I working in a new version using "Ansible" as a provisioner.

I use the vagrant boxes to onboard the devs, I have implemented this for a Bank and they still used for the dev team.

Check also this repo  : https://github.com/ahmed-musallam/AEM-UP
If any question: https://www.linkedin.com/in/adolfodepazvela/
Thanks

**Comment by jmfury** [comment]
Wow that is awesome! Very interesting, I recently became aware of a couple Vagrant boxes using Puppet to do what I assume to be a similar thing. 

Thanks for the links and once again for putting this out here!
